[theme]
base = "dark"
primaryColor = "#ff4fd8"
backgroundColor = "#09051a"
secondaryBackgroundColor = "#15102b"
textColor = "#f8f7ff"
font = "sans serif"

[server]
maxUploadSize = 12
headless = true

[browser]
gatherUsageStats = false
